export const AuditEventType = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGIN_FAILED: "LOGIN_FAILED",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
  EMAIL_VERIFY: "EMAIL_VERIFY",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",
  ROLE_CHANGE: "ROLE_CHANGE",
  ACCOUNT_LOCK: "ACCOUNT_LOCK",
  ACCOUNT_UNLOCK: "ACCOUNT_UNLOCK",
  API_CALL: "API_CALL",
  MAGIC_LINK_REQUEST: "MAGIC_LINK_REQUEST",
  PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
} as const;

export type AuditEventType = (typeof AuditEventType)[keyof typeof AuditEventType];
